// sync-library.mjs — pulls curated Obsidian notes into the website as the
// "Dog Health A-Z" content. Converts each note's markdown -> HTML at build time
// and writes lib/library-data.ts (no runtime markdown dependency).
//
// Re-run whenever you update the notes in Obsidian:
//   node scripts/sync-library.mjs
//
// To add a topic: drop a note in the vault and add an entry to TOPICS below.
import { readFileSync, writeFileSync } from 'fs'
import { join } from 'path'
import { homedir } from 'os'
import { marked } from 'marked'

const VAULT = process.env.OBSIDIAN_BRAIN_VAULT || join(homedir(), 'Documents', 'Obsidian Vault')

// Curated A-Z topics sourced from the vault. summary = plain-language one-liner
// shown on the index card. letter controls the A-Z bucket.
const TOPICS = [
  {
    slug: 'flea-tick-and-isoxazolines', title: 'Fleas, Ticks & Isoxazolines', letter: 'F',
    emoji: '🚩', tag: 'Parasite Prevention',
    summary: 'How Bravecto/NexGard/Simparica actually work, their risks, and natural flea & tick prevention that repels before the bite.',
    file: 'commonsensedog knowledge/Flea Tick and Isoxazoline Safety.md',
  },
  {
    slug: 'supplements-by-benefit', title: 'Supplements (by what they help)', letter: 'S',
    emoji: '💊', tag: 'Supplements',
    summary: 'Joint, anti-inflammatory, gut, immune & calming supplements — what the canine evidence actually shows for each.',
    file: 'commonsensedog knowledge/Supplement Evidence by Benefit.md',
  },
  {
    slug: 'processing-methods', title: 'Food Processing Methods', letter: 'P',
    emoji: '🔥', tag: 'Nutrition',
    summary: 'Raw, freeze-dried, gently cooked, kibble — how each is made and what processing does to the nutrients.',
    file: 'Brain/Nutrition/Processing Methods.md',
  },
  {
    slug: 'vitamins-and-minerals', title: 'Vitamins & Minerals', letter: 'V',
    emoji: '🧪', tag: 'Nutrition',
    summary: 'Good vs bad forms — why chelated minerals beat oxides/sulfates, and which synthetic vitamins to avoid.',
    file: 'Brain/Nutrition/Vitamins and Minerals.md',
  },
  {
    slug: 'lipomas-and-organ-diet', title: 'Lipomas & Organ-Support Diet', letter: 'L',
    emoji: '🧬', tag: 'Nutrition',
    summary: 'The diet levers that slow fatty-tumor growth — low carb, a 5:1 omega ratio, and "like feeds like" organ support.',
    file: 'Brain/Nutrition/Organs and Lipoma Diet.md',
  },
  {
    slug: 'nutrition-philosophy', title: 'Nutrition Philosophy', letter: 'N',
    emoji: '🥩', tag: 'Nutrition',
    summary: 'The whole-food-first, inflammation-is-the-root approach behind every recommendation on this site.',
    file: 'Brain/Nutrition/Nutrition Philosophy.md',
  },
  {
    slug: 'hersheys-health-protocol', title: "Hershey's Health Protocol", letter: 'H',
    emoji: '🐾', tag: 'Real Routines',
    summary: "Exactly what Kyle does for his own 75lb Lab — diet, supplements, dental, and the natural flea/tick stack.",
    file: 'Brain/People/Hershey Health Protocol.md',
  },
]

function cleanMarkdown(md) {
  return md
    .replace(/^---\n[\s\S]*?\n---\n?/, '') // YAML frontmatter
    .replace(/^#\s+.*(\n|$)/, '')          // leading H1 (the page shows the title already)
    .trim()
}

const out = []
for (const t of TOPICS) {
  let md
  try {
    md = readFileSync(join(VAULT, t.file), 'utf-8')
  } catch {
    console.warn(`⚠️  skipping (note not found): ${t.file}`)
    continue
  }
  const html = marked.parse(cleanMarkdown(md))
  out.push({
    slug: t.slug, title: t.title, summary: t.summary, letter: t.letter,
    emoji: t.emoji, tag: t.tag, source: t.file, contentHtml: html,
  })
  console.log(`✓ ${t.title}`)
}

const file = `// AUTO-GENERATED by scripts/sync-library.mjs — do not edit by hand.
// Source: curated Obsidian notes. Re-run \`node scripts/sync-library.mjs\` to update.

export interface LibraryTopic {
  slug: string
  title: string
  summary: string
  letter: string
  emoji: string
  tag: string
  source: string
  contentHtml: string
}

export const libraryTopics: LibraryTopic[] = ${JSON.stringify(out, null, 2)}
`

writeFileSync(join(process.cwd(), 'lib', 'library-data.ts'), file, 'utf-8')
console.log(`\n📚 Wrote lib/library-data.ts — ${out.length} topics.`)
